language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r backend/requirements.txt
# command to run tests
env:
  - PYTHONPATH=backend/
script:
  - python -m pytest ./backend/tests